### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtPrintSupport'

### ISSUE THREAD

**Issue by lkl22** [lkl22/CommonTools#1]
Traceback (most recent call last):
  File "widget\algorithm\sort\SelectionSortDialog.py", line 228, in jumpAlgoDesc
    from widget.algorithm.AlgorithmDescDialog import AlgorithmDescDialog
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "widget\algorithm\AlgorithmDescDialog.py", line 5, in <module>
    from PyQt5.Qsci import QsciScintilla, QsciLexerPython, QsciLexer, QsciLexerJavaScript, QsciLexerJava, QsciLexerCPP, \
ModuleNotFoundError: No module named 'PyQt5.QtPrintSupport'

**Comment by lkl22** [comment]
AlgorithmDescDialog.py 导包 `from PyQt5 import QtPrintSupport`

```python
# python 3.x
# Filename: AlgorithmDescDialog.py
# 定义一个AlgorithmDescDialog类实现算法描述和代码实现功能
from PyQt5 import QtPrintSupport
from PyQt5.Qsci import QsciScintilla, QsciLexerPython, QsciLexer, QsciLexerJavaScript, QsciLexerJava, QsciLexerCPP
from constant.WidgetConst import *
from util.Uiautomator import *
```
