### ISSUE TITLE
Preparing metadata (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by lkl22** [lkl22/CommonTools#4]
详细错误信息如下：
```
Collecting PyQt5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 34.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\lkl\AppData\Local\Temp\pip-build-env-3e6z5qqc\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\lkl\AppData\Local\Temp\pip-build-env-3e6z5qqc\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
          self.apply_user_defaults(tool)
        File "C:\Users\lkl\AppData\Local\Temp\pip-install-hchebq2q\pyqt5_067971190f754191bc8d630ccbd4894c\project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\lkl\AppData\Local\Temp\pip-build-env-3e6z5qqc\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\lkl\AppData\Local\Temp\pip-build-env-3e6z5qqc\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\lkl\AppData\Local\Temp\pip-build-env-3e6z5qqc\overlay\Lib\site-packages\pyqtbuild\builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

**Comment by lkl22** [comment]
缺少依赖，先安装依赖

> pip install wheel

再安装pyqt5
